s3:
  bucket: example-bucket-name
  region: us-west-1
  useSDKCreds: true
  keyFormat: >-
    prefix/
      {{workflow.creationTimestamp.Y}}-
      {{workflow.creationTimestamp.m}}-
      {{workflow.creationTimestamp.d}}/
    {{workflow.name}}
