apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    trigger-pipeline:
      port: "12000"
      endpoint: /greet-and-count
      method: POST

