apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: count-wf-template
spec:
  entrypoint: count-all
  arguments:
    parameters:
    - {name: timestamp, value: "2000-01-01 12:00:00"}
    - name: hello-key-prefix
      valueFrom:
        configMapKeyRef:
          name: example-parameters
          key: hello-key-prefix
    - name: goodbye-key-prefix
      valueFrom:
        configMapKeyRef:
          name: example-parameters
          key: goodbye-key-prefix

  templates:
  - name: count-all
    steps:
    - - name: debug
        template: debug
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.hello-key-prefix}}\
                    /{{=sprig.replace(' ','/',sprig.trunc(13,workflow.parameters.timestamp))}}"
    - - name: list-hello-files
        template: list-files
        arguments:
          artifacts:
          - name: folder
            s3:
              key: "{{workflow.parameters.hello-key-prefix}}\
                    /{{=sprig.replace(' ','/',sprig.trunc(13,workflow.parameters.timestamp))}}"
      - name: list-goodbye-files
        template: list-files
        arguments:
          artifacts:
          - name: folder
            s3:
              key: "{{workflow.parameters.goodbye-key-prefix}}\
                    /{{=sprig.replace(' ','/',sprig.trunc(13,workflow.parameters.timestamp))}}"

  - name: list-files
    inputs:
      artifacts:
      - {name: folder, path: "/workdir"}
    script:
      image: bash
      command: [bash]
      source: |
        ls -lah /workdir
  - name: debug
    inputs:
      parameters:
      - {name: message, default: ''}
    script:
      image: bash
      command: [bash]
      source: |
        echo {{inputs.parameters.message}}
