apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: goodbye-wf-template
spec:
  artifactRepositoryRef:
    configMap: example-artifact-repositories
    key: example-goodbye-s3
  entrypoint: replace-text
  arguments:
    parameters:
    - {name: bucket, value: example-bucket}
    - {name: key, value: example/input.txt}
 
  templates:
  - name: replace-text
    arguments:
      artifacts:
      - name: input-file
        path: /tmp/in.txt
        s3:
          bucket: "{{workflow.parameters.bucket}}"
          key: "{{workflow.parameters.key}}"
    container:
      image: replace-text:latest
      command: [python, rt.py]
      args:
      - --input-file
      - /tmp/in.txt
      - --output-file
      - /tmp/out.txt
      - --search
      - hello
      - --replace
      - goodbye
    outputs:
      artifacts:
      - name: output-file
        path: /tmp/out.txt
