apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: count-all
spec:
  dependencies:
    - name: cal-dep
      eventSourceName: calendar
      eventName: ten-past-hour
      transform:
      #set userPayload.targetTime to 1 hour before the event
        script: |-
          pattern="(%d+)-(%d+)-(%d+) (%d+):(%d+):(%d+)"
          year,month,day,hour,min,sec=event.eventTime:match(pattern)
          target_time=os.time({day=day,month=month,year=year,hour=hour-1,min=min,sec=sec})
          event.userPayload.targetTime=os.date("%Y-%m-%d %H:%M:%S")
  triggers:
    - template:
        name: webhook-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: count-
              spec:
                arguments:
                  parameters:
                  - {name: timestamp, value: ""}
                workflowTemplateRef:
                  name: count-wf-template
          parameters:
            - src:
                dependencyName: cal-dep
                dataKey: userPayload.targetTime
              dest: spec.arguments.parameters.0.value
