apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sqs
spec:
  dependencies:
    - name: sqs-hello-dep
      eventSourceName: s3-sqs
      eventName: object-created
  triggers:
  - template:
      name: replace-trigger
      conditions: sqs-hello-dep
      argoWorkflow:
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: run-goodbyes-
            spec:
              arguments:
                parameters:
                - {name: records, value: "[]"}
              workflowTemplateRef:
                name: run-goodbyes-wf-template
        parameters:
        - src:
            dependencyName: sqs-hello-dep
            dataKey: body.Records
          dest: spec.arguments.parameters.0.value
