apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sqs
spec:
  dependencies:
    - name: sqs-hello-dep
      eventSourceName: s3-sqs
      eventName: object-created
      filters:
        data:
        - path: body.Records.0.s3.bucket.name
          type: string
          value: ["example-bucket-name"]
        - path: body.Records.0.s3.object.key
          type: string
          value:
          - "^prefix\/hellos\/"
  triggers:
  - template:
      name: sqs-workflow-replace
      conditions: sqs-hello-dep
      argoWorkflow:
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: replace-
            spec:
              arguments:
                parameters:
                - {name: bucket, value: example-bucket}
                - {name: key, value: ''}
              workflowTemplateRef:
                name: goodbye-wf-template
        parameters:
        - src:
            dependencyName: sqs-hello-dep
            dataKey: body.Records.0.s3.bucket.name
          dest: spec.arguments.parameters.0.value
        - src:
            dependencyName: sqs-hello-dep
            dataKey: body.Records.0.s3.object.key
          dest: spec.arguments.parameters.1.value
