apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: s3-sqs
spec:
  sqs:
    object-created:
      jsonBody: true
      region: "us-east-1"
      queue: "example-queue"
      waitTimeSeconds: 20
