apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: start-pipeline
spec:
  dependencies:
    - name: wh-dep
      eventSourceName: webhook
      eventName: greet
    - name: cal-dep
      eventSourceName: calendar
      eventName: every-seven-minutes
      transform:
      #randomize metadata.names
        script: |-
          math.randomseed(os.time())
          ea = {"a","b","c","d","e","f","g","h","i","j","k","l","m","n","0","p"}
          i = math.random(1,#ea-2)
          j = math.random(i,#ea)
          names = ''
          for n=i,j do
            names = names..ea[n]
            if n~=j then
              names = names..","
            end
          end
          event.metadata.names = names
          return event
  triggers:
    - template:
        conditions: "wh-dep || cal-dep"
        name: start-pipeline-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: greet-
              spec:
                arguments:
                  parameters:
                  - {name: names, value: "to,be,replaced"}
                workflowTemplateRef:
                  name: hello-wf-template
          parameters:
            - src:
                dependencyName: cal-dep
                dataKey: metadata.names
                value: "Default,Names"
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: wh-dep
                dataKey: body.names
              dest: spec.arguments.parameters.0.value
