apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: start-pipeline
spec:
  dependencies:
    - name: wh-dep
      eventSourceName: webhook
      eventName: greet
    - name: cal-dep
      eventSourceName: calendar
      eventName: every-seven-minutes
  triggers:
    - template:
        conditions: "wh-dep || cal-dep"
        name: webhook-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: greet-
              spec:
                arguments:
                  parameters:
                  - {name: names, value: "to,be,replaced"}
                workflowTemplateRef:
                  name: hello-wf-template
          parameters:
            - src:
                dependencyName: wh-dep
                dataKey: body.names
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: cal-dep
                dataKey: body.userPayload.names
                value: "Default,Names"
              dest: spec.arguments.parameters.0.value
