apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: container-templates
spec:
  templates:
  - name: greet
    inputs:
      parameters:
      - {name: key-prefix, default: ''}
      - {name: greeting, default: default}
      - {name: names, default: 'Alice,Bob'}
    container:
      image: greetings:latest
      command: [python, greet.py]
      args:
        - --names
        - "{{inputs.parameters.names}}"
        - --greeting
        - "{{inputs.parameters.greeting}}"
        - --output-file
        - /tmp/out.txt
    outputs:
      artifacts:
      - name: output-file
        path: /tmp/out.txt
        archive:
          none: {}

###############################################################

  - name: replace-text
    inputs:
      parameters:
      - {name: input-key}
      - {name: key-prefix, default: ''}
      - {name: search, default: default}
      - {name: replace, default: default}
      artifacts:
      - name: input-file
        path: /tmp/in.txt
    container:
      image: replace-text:latest
      command: [python, rt.py]
      args:
      - --input-file
      - /tmp/in.txt
      - --output-file
      - /tmp/out.txt
      - --search
      - "{{inputs.parameters.search}}"
      - --replace
      - "{{inputs.parameters.replace}}"
    outputs:
      artifacts:
      - name: output-file
        path: /tmp/out.txt
        archive:
          none: {}
###############################################################

  - name: count
    inputs:
      parameters:
      - {name: string, default: default}
      artifacts:
      - name: input-file
        path: /tmp/in.txt
    container:
      image: count:latest
      command: [python, count.py]
      args: ['--input-file', '/tmp/in.txt', '--string', "{{inputs.parameters.string}}"]
