apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: goodbye-wf-template
spec:
  entrypoint: goodbye-wf
  arguments:
    parameters:
    - {name: cm-name, value: default-cm}
    - {name: file, value: ''}
 
  templates:
  - name: goodbye-wf
    template: replace-text
    arguments:
      parameters:
      - name: bucket
        valueFrom:
          configMapKeyRef:
            name: "{{workflow.parameters.cm-name}}"
            key: bucket
      - name: roleARN
        valueFrom:
          configMapKeyRef:
            name: "{{workflow.parameters.cm-name}}"
            key: roleARN
      - name: key
        value: "{{workflow.parameters.input-payload}}"
      - {name: search, value: hello}
      - {name: replace, value: goodbye}

  - name: replace-text
    inputs:
      parameters:
      - {name: bucket-name}
      - {name: roleARN}
      - {name: key}
      - {name: key-prefix, default: ''}
      - {name: search, default: default}
      - {name: replace, default: default}
      artifacts:
      - name: input-file
        path: /tmp/in.txt
        s3:
          endpoint: s3.amazonaws.com
          bucket: "{{inputs.parameters.bucket-name}}"
          key: "{{inputs.parameters.key}}"
          roleARN: "{{inputs.parameters.roleARN}}"
    container:
      image: replace-text:latest
      command: [python, rt.py]
      args:
      - --input-file
      - /tmp/in.txt
      - --output-file
      - /tmp/out.txt
      - --search
      - "{{inputs.parameters.search}}"
      - --replace
      - "{{inputs.parameters.replace}}"
    outputs:
      artifacts:
      - name: output-file
        path: /tmp/out.txt
        s3:
          endpoint: s3.amazonaws.com
          bucket: "{{inputs.parameters.bucket-name}}"
          key: >-
            {{inputs.parameters.key-prefix}}/
              {{workflow.creationTimestamp.Y}}-
              {{workflow.creationTimestamp.m}}-
              {{workflow.creationTimestamp.d}}/
            {{workflow.name}}/
            {{pod.name}}.txt
          roleARN: "{{inputs.parameters.roleARN}}"
