apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-wf-template
spec:
  entrypoint: hello-wf
  arguments:
    parameters:
    - {name: cm-name, value: default-cm}
    - {name: input-payload, value: '[]'}

  templates:
  - name: hello-wf
    template: greet
    arguments:
      parameters:
      - name: bucket
        valueFrom:
          configMapKeyRef:
            name: "{{workflow.inputs.parameters.cm-name}}"
            key: bucket
      - name: roleARN
        valueFrom:
          configMapKeyRef:
            name: "{{workflow.inputs.parameters.cm-name}}"
            key: roleARN
      - {name: greeting, value: hello}
      - {name: names, value: "{{item}}"}
    withParam: "{{workflow.inputs.parameters.input-payload}}"

  - name: greet
    inputs:
      parameters:
      - {name: bucket-name}
      - {name: roleARN}
      - {name: key-prefix, default: ''}
      - {name: greeting, default: default}
      - {name: names, default: 'Alice,Bob'}
    container:
      image: greetings:latest
      command: [python, greet.py]
      args:
      - --names
      - "{{inputs.parameters.names}}"
      - --greeting
      - "{{inputs.parameters.greeting}}"
      - --output-file
      - /tmp/out.txt
    outputs:
      artifacts:
      - name: output-file
        path: /tmp/out.txt
        archive:
          none: {}
        s3:
          endpoint: s3.amazonaws.com
          bucket: "{{inputs.parameters.bucket-name}}"
          key: >-
            {{inputs.parameters.key-prefix}}/
              {{workflow.creationTimestamp.Y}}-
              {{workflow.creationTimestamp.m}}-
              {{workflow.creationTimestamp.d}}/
            {{workflow.name}}/
            {{pod.name}}.txt
          roleARN: "{{inputs.parameters.roleARN}}"
