apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hello-wf-template.yaml
- goodbye-wf-template.yaml

configMapGenerator:
- name: default-cm
  literals:
  - bucket=default
  - roleARN=default
  - table-name=default
  - db-connection-secret=db-connection-example
  options:
    disableNameSuffixHash: true
    labels:
        workflows.argoproj.io/configmap-type: Parameter

configurations:
- kustomizeconfig/workflow.yaml

images:
- name: count
  newTag: latest
- name: greetings
  newTag: latest
- name: replace-text
  newTag: latest
