apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: s3-new-files-sqs
spec:
  sqs:
   example-without-credentials:
     region: "us-east-1"
     queue: "my-fake-queue-2"
     waitTimeSeconds: 20
