apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- container-templates.yaml
- script-templates.yaml
- single-wf-template.yaml
- wh-eventsource.yaml
- wh-sensor.yaml

generators:
- generators/example-parameters.yaml
- generators/example-artifacts.yaml
- generators/example-db-connect.yaml
  
configurations:
- kustomizeconfig/workflow.yaml

images:
- name: count
  newTag: latest
- name: greetings
  newTag: latest
- name: replace-text
  newTag: latest
