apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- container-templates.yaml
- script-templates.yaml
- single-wf-template.yaml
- eventsource.yaml
- sensor.yaml

configurations:
- kustomizeconfig/workflow.yaml

images:
- name: count
  newName: ghcr.io/nikita-akuity/count
  newTag: latest
- name: greetings
  newName: ghcr.io/nikita-akuity/greetings
  newTag: latest
- name: replace-text
  newName: ghcr.io/nikita-akuity/replace-text
  newTag: latest
