apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- container-templates.yaml
- script-templates.yaml
- single-wf-template.yaml
- eventsource.yaml
- sensor.yaml

configMapGenerator:
- name: default-cm
  literals:
  - bucket=default
  - roleARN=default
  - table-name=default
  - db-connection-secret=db-connection-example
  options:
    disableNameSuffixHash: true
    labels:
        workflows.argoproj.io/configmap-type: Parameter

secretGenerator:
- name: db-connection-example
  literals:
  - DB_HOST=db.hostnam
  - DB_PORT=3600
  - DB_NAME=database_name
  - DB_USER=database_user
  - DB_PASSWORD=secretPassW0rd
  
configurations:
- kustomizeconfig/workflow.yaml

images:
- name: count
  newTag: latest
- name: greetings
  newTag: latest
- name: replace-text
  newTag: latest
