apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- container-templates.yaml
- script-templates.yaml
- single-wf-template.yaml
- eventsource.yaml
- sensor.yaml

configMapGenerator:
  - name: default-cm
    literals:
    - bucket=default
    - roleARN=default
    options:
      disableNameSuffixHash: true
      labels:
         workflows.argoproj.io/configmap-type: Parameter

configurations:
- kustomizeconfig/workflow.yaml

images:
- name: count
  newTag: latest
- name: greetings
  newTag: latest
- name: replace-text
  newTag: latest
