apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- workflows
- events

generators:
- generators/example-parameters.yaml
- generators/example-artifacts.yaml
- generators/example-db-connect.yaml
  
configurations:
- kustomizeconfig/workflow.yaml

images:
- name: count
  newTag: latest
- name: greetings
  newTag: latest
- name: replace-text
  newTag: latest
