apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: single-wf-template
spec:
  entrypoint: single-wf
  arguments:
    parameters:
    - {name: input-payload, value: "[]"}
    - name: mysql-table-name
      valueFrom:
        configMapKeyRef:
          name: example-parameters
          key: table-name
    - name: mysql-connection-secret
      value: example-db-connect
  
  artifactRepositoryRef:
    configMap: example-artifact-repositories
    key: example-s3
 
  templates:
  - name: single-wf
    steps:
    - - name: process-item
        template: branch
        arguments:
          parameters:
          - {name: names, value: "{{item}}"}
        withParam: "{{workflow.parameters.input-payload}}"

    - - name: sum-hellos
        templateRef:
          name: script-templates
          template: sum
        arguments:
          parameters:
          - {name: numbers, value: "{{steps.process-item.outputs.parameters.count-hellos}}"}

      - name: sum-goodbyes
        templateRef:
          name: script-templates
          template: sum
        arguments:
          parameters:
          - {name: numbers, value: "{{steps.process-item.outputs.parameters.count-goodbyes}}"}

    - - name: write-result
        templateRef:
          name: script-templates
          template: write-to-db
        arguments:
          parameters:
          - name: table-name
            value: "{{workflow.parameters.mysql-table-name}}"
          - name: db-connection-secret
            value: "{{workflow.parameters.mysql-connection-secret}}"
          - {name: sum-hello, value: "{{steps.sum-hellos.outputs.result}}"}
          - {name: sum-goodbye, value: "{{steps.sum-goodbyes.outputs.result}}"}

  - name: branch
    inputs:
      parameters:
      - {name: names}
    steps:
    - - name: hellos
        templateRef:
          name: container-templates
          template: greet
        arguments:
          parameters:
          - {name: greeting, value: hello}
          - {name: names, value: "{{inputs.parameters.names}}"}
    - - name: goodbyes
        templateRef:
          name: container-templates
          template: replace-text
        arguments:
          parameters:
          - {name: search, value: hello}
          - {name: replace, value: goodbye}
          - {name: input-key, value: "{{item}}"}
          artifacts:
          - name: input-file
            from: "{{steps.hellos.outputs.artifacts.output-file}}"    
    - - name: count-hellos
        templateRef:
          name: container-templates
          template: count
        arguments:
          parameters:
          - {name: string, value: hello}
          artifacts:
          - name: input-file
            from: "{{steps.hellos.outputs.artifacts.output-file}}"    
      - name: count-goodbyes
        templateRef:
          name: container-templates
          template: count
        arguments:
          parameters:
          - {name: string, value: goodbye}
          artifacts:
          - name: input-file
            from: "{{steps.goodbyes.outputs.artifacts.output-file}}"
    outputs:
      parameters:
      - name: count-hellos
        valueFrom:
          parameter: "{{steps.count-hellos.outputs.result}}"
      - name: count-goodbyes
        valueFrom:
          parameter: "{{steps.count-goodbyes.outputs.result}}"
