apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: single-wf-template
spec:
  entrypoint: single-wf
  arguments:
    parameters:
    - {name: cm-name, value: default-cm}
    - {name: input-payload, value: "[]"}
  templates:
  - name: single-wf
    dag:
      tasks:
      - name: parse-input
        templateRef:
          name: demo-templates
          template: parse-input
      - name: greetings
        templateRef:
          name: demo-templates
          template: greet
        arguments:
          parameters:
          - name: bucket
            valueFrom:
              configMapKeyRef:
                name: "{{workflow.inputs.parameters.cm-name}}"
                key: bucket
          - name: roleARN
            valueFrom:
              configMapKeyRef:
                name: "{{workflow.inputs.parameters.cm-name}}"
                key: roleARN
          - {name: greeting, value: hello}
          - {name: names, value: "{{item}}"}
        withParam: "{{tasks.parse-input.outputs.result}}"
      - name: goodbyes
        templateRef:
          name: demo-templates
          template: replace-text
        arguments:
          parameters:
          - {name: search, value: hello}
          - {name: replace, value: goodbye}
          - {name: filename, value: "{{item}}"}
        withParam: "{{tasks.greetings.outputs.parameters.filename}}"
      - name: count-hellos
        templateRef:
          name: demo-templates
          template: count
        arguments:
          parameters:
          - {name: string, value: hello}
          - {name: filename, value: "{{item}}"}
        withParam: "{{tasks.greetings.outputs.parameters.filename}}"
      - name: count-goodbyes
        templateRef:
          name: demo-templates
          template: count
        arguments:
          parameters:
          - {name: string, value: goodbye}
          - {name: filename, value: "{{item}}"}
        withParam: "{{tasks.goodbyes.outputs.parameters.filename}}"
      - name: sum-hellos
        templateRef:
          name: demo-templates
          template: sum
        arguments:
          parameters:
          - {name: list, value: "{{tasks.count-hellos.outputs.result}}"}
      - name: sum-goodbyes
        templateRef:
          name: demo-templates
          template: sum
        arguments:
          parameters:
          - {name: list, value: "{{tasks.count-goodbyes.outputs.result}}"}
      - name: write-result
        templateRef:
          name: demo-templates
          template: write-to-db
        arguments:
          parameters:
          - {name: hello_sum, value: "{{tasks.sum-hellos.outputs.result}}"}
          - {name: goodbye_sum, value: "{{tasks.sum-goodbyes.outputs.result}}"}
