s3:
  endpoint: s3.amazonaws.com
  bucket: example-bucket-name
  region: us-west-1
  useSDKCreds: true
  keyFormat: "prefix/hellos\
    /{{workflow.creationTimestamp.Y}}-\
    {{workflow.creationTimestamp.m}}-\
    {{workflow.creationTimestamp.d}}\
    /{{workflow.creationTimestamp.H}}"
