name: Build and Promote
on:
  push:
    branches:
      - main
      - feature/**
    paths:
      - images/**
      - .github/**

jobs:
  build-job:
    name: Build, Test and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [count, greetings, replace-text]
    permissions:
      contents: read
      packages: write

    outputs:
      tags: ${{ steps }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.folder }}
          tags: |
            type=sha
      - name: Login to image registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_PAT }}
      - name: Build and test
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:images/${{ matrix.folder }}"
          target: test
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.folder }}:test
      - name: Build and push
        id: push-image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:images/${{ matrix.folder }}"
          target: app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  promote-job:
    name: Promote Images to Dev Environment
    runs-on: ubuntu-latest
    needs: build-job
    env:
      TAGS: ${{ needs.build-job.outputs.tags }}
    strategy:
      matrix:
        include:
        - delivery-repo: github.com/nikita-akuity/demo-workflow-delivery.git
          kustomization-path: demo-workflow-delivery/single-workflow/env/dev
    steps:
    - uses: imranismail/setup-kustomize@v1
    - name: Kustomize
      run: |
        echo $TAGS
