name: Update Kustomize Base
on:
  push:
    branches:
      - main
    paths:
      - manifests/**

jobs:
  promote-job:
    name: Update Base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - folder: single-workflow
          delivery-repo: github.com/nikita-akuity/demo-workflow-delivery
          kustomization-path: demo-workflow-delivery/single-workflow/base
    steps:
    - uses: chrisdickinson/setup-yq@latest
    - name: Run yq
      run: |
        set -ex
        git config --global user.name "Deploy Bot"
        git config --global user.email "no-reply@akuity.io"
        git clone https://bot:${{ secrets.DEPLOY_PAT }}@${{ matrix.delivery-repo }} 
        cd ${{ matrix.kustomization-path }}
        yq -i '.resources[0]="${{ github.server_url }}/${{ github.repository }}//manifests/${{ matrix.folder }}/?ref=${{ github.sha }}"' kustomization.yaml
        git commit -a -m "Update ${{ matrix.folder }} base to ${{ github.repository }}@${{ github.sha }}"
        git push origin main
